In [1]:
import pandas as pd
import numpy as np

In [2]:
x=[1,2,3]
X=np.array([[1,1],[1,2],[1,3]])
print(X)
X.shape

[[1 1]
 [1 2]
 [1 3]]


(3, 2)

In [3]:
print(X.T)
(X.T).shape

[[1 1 1]
 [1 2 3]]


(2, 3)

In [4]:
Y=np.array([2,3,5])
print(Y)
Y.shape

[2 3 5]


(3,)

In [5]:
np.linalg?

Type:        module
String form: <module 'numpy.linalg' from '/opt/anaconda3/lib/python3.11/site-packages/numpy/linalg/__init__.py'>
File:        /opt/anaconda3/lib/python3.11/site-packages/numpy/linalg/__init__.py
Docstring:  
``numpy.linalg``

The NumPy linear algebra functions rely on BLAS and LAPACK to provide efficient
low level implementations of standard linear algebra algorithms. Those
libraries may be provided by NumPy itself using C versions of a subset of their
reference implementations but, when possible, highly optimized libraries that
take advantage of specialized processor functionality are preferred. Examples
of such libraries are OpenBLAS, MKL (TM), and ATLAS. Because those libraries
are multithreaded and processor dependent, environmental variables and external
packages such as threadpoolctl may be needed to control the number of threads
or specify the processor architecture.

- OpenBLAS: https://www.openblas.net/
- threadpoolctl: https://github.com/joblib/threadpoolc

In [6]:
val=(X.T@X)
val

array([[ 3,  6],
       [ 6, 14]])

In [7]:
inv=np.linalg.inv(val)
inv

array([[ 2.33333333, -1.        ],
       [-1.        ,  0.5       ]])

In [8]:
Y@X.T

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [9]:
X.T@Y

array([10, 23])

In [10]:
m,b=inv@(X.T@Y)
print('m(slope)=',m,'b(intercept)=',b)

m(slope)= 0.3333333333333286 b(intercept)= 1.5


In [ ]:
# y=mx+b

#x=[1,2,3]
#y=[2,3,5]
#set-1
# 2=.33(1)+1.5
#2 = 1.88
#Here 2 is the actaul value and 1.88 is the predicted value

#set-2
#3=.33(2)+1.5
#3=.66+1.5
#3=2.16
#Here 3 is the actaul value and 2.16 is the predicted value

#set-3
#5=.33(3)+1.5
#5=.99+1.5
#5=2.49
#Here 35 is the actaul value and 2.49 is the predicted value



In [11]:
X=np.array([[3,2],[4,2]])
Y=np.array([10,4])

In [12]:
print(X.shape)
print(Y.shape)

(2, 2)
(2,)


In [13]:
X.T

array([[3, 4],
       [2, 2]])

In [14]:
X.T@X

array([[25, 14],
       [14,  8]])

In [15]:
np.linalg.inv(X.T@X)

array([[ 2.  , -3.5 ],
       [-3.5 ,  6.25]])

In [16]:
X.T@Y

array([46, 28])

In [17]:
np.linalg.inv(X.T@X)@(X.T@Y)

array([-6., 14.])

In [18]:
b,m=np.linalg.inv(X.T@X)@(X.T@Y)
#print('b=',abs(b),'m=',abs(m))
print('b=',(b),'m=',(m))


b= -6.000000000000034 m= 14.000000000000053


In [ ]:
#y=mx+c


In [20]:
pd.read_csv('tips_data.csv')

no_of_customers  no_of_server  bill_amt  tips_amt
0               10             3     10000       500
1                5             2     10000      1000
2               25             5     15000      1000

In [21]:
X=np.array([[1,10,3,1000],[1,5,2,10000],[1,25,5,15000]])
print(X,X.shape)

[[    1    10     3  1000]
 [    1     5     2 10000]
 [    1    25     5 15000]] (3, 4)


In [24]:
Y=np.array([500,1000,1000])

In [25]:
np.linalg.inv(X.T@X)@(X.T@Y)

array([ 3.072e+03,  1.280e+02, -1.024e+03,  3.125e-02])

In [ ]:
tip_amount = 3072 + 128*no_of_customers -1024*no_of_servers + .03125*bill_amt
