In [2]:
print('Wednesday Class 2')

Wednesday Class 2


In [6]:
#Tuples
a=(1,'Two',3.0,4)
print(a,type(a))
print(a[0])
a[0]=10

(1, 'Two', 3.0, 4) <class 'tuple'>
1


TypeError: 'tuple' object does not support item assignment

In [7]:
a=tuple() # Creating empty type
print(a,type(a))

() <class 'tuple'>


In [9]:
a=()
print(a,type(a))


() <class 'tuple'>


In [10]:
a=[]
print(a,type(a))

[] <class 'list'>


In [11]:
a=(1,2,3,4) #Homogenous tuple
b=(1,'Two',3.0,4) #Hetrogenous tuple

In [13]:
a=tuple([1,2,3])
print(a,type(a))


(1, 2, 3) <class 'tuple'>


In [14]:
a=tuple(1,2,3)
print(a,type(a))

TypeError: tuple expected at most 1 argument, got 3

In [16]:
a[:2]

(1, 2)

In [18]:
a[::2]

(1, 3)

In [23]:
a[::-1]

(3, 2, 1)

In [29]:
a=(1,2,3)
b=(10,20,30)
print(a+b)

(1, 2, 3, 10, 20, 30)


In [30]:
print (a*2,type(a)) # here tuples are not mutable hence it do the tuple appending (i.e) a*2 = a+a


(1, 2, 3, 1, 2, 3) <class 'tuple'>


In [33]:
a=[1,2,3]
print (a*2,type(a)) 

[1, 2, 3, 1, 2, 3] <class 'list'>


In [37]:
a=(1,2,3)
c=a*50
c

(1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3)

In [40]:
print (len(c))
#[start:stop:step]

print(c[2:150:3])
print(c[2::3]) # Blank in stop goes till end, Blank in step, increments by 1


150
(3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3)


In [42]:
c.count(2) # To find the number of occurance of 2 in the tuple

50

In [43]:
a=(1,2,3)
print(3 in a) # Check whether value exist in the tuple use IN operator

True


In [45]:
a=(1,2,3)
print(5 in a) # Check whether value exist in the tuple use IN operator

False


In [47]:
a=(1,2,3)
print(5 not in a) # Check whether value exist in the tuple use IN operator

True


In [63]:
person = ('Rahul',6,'manager')
print(person,type(person))

('Rahul', 6, 'manager') <class 'tuple'>


In [54]:
#Method 1 - Unpacking a tuple and assigning to multiple variables
name,id,role = person
print(name,id,role)
print(type(name),type(id),type(role),type(person))

Rahul 6 manager
<class 'str'> <class 'int'> <class 'str'> <class 'tuple'>


In [56]:
#Method 2 - Just Unpacking the tuple 
print(*person)

Rahul 6 manager


In [62]:
a,b,c=person
print(a,b,c)

Rahul 6 manager


In [68]:
person = ('Rahul',6,'manager,cricketer,coach')
name,id,role = person
print(name)
print(id)
print(role)
print(type(name),type(id),type(role),type(person))

Rahul
6
manager,cricketer,coach
<class 'str'> <class 'int'> <class 'str'> <class 'tuple'>


In [70]:
#List - []
#tuple - ()
#set & Dictionary - {}


In [72]:
a={1,'Two',3.0,4}
print(a,type(a))

{1, 'Two', 3.0, 4} <class 'set'>


In [74]:
a={1,2,3,4,1,2}
print(a)

{1, 2, 3, 4}


In [77]:
a={}
print(type(a))
a=set()
print(type(a))


<class 'dict'>
<class 'set'>


In [79]:
a.add(1)
print(a)
print(type(a))

{1}
<class 'set'>


In [80]:
a.add(2)
print(a)
print(type(a))

{1, 2}
<class 'set'>


In [81]:
a.remove(2)
print(a)
print(type(a))

{1}
<class 'set'>


In [82]:
a={1,2,3,4,5}
print(a)
del a
print(a)

{1, 2, 3, 4, 5}


NameError: name 'a' is not defined

In [85]:
a={1,2,3,4,5}
print(a)
a.clear()
print(a)


{1, 2, 3, 4, 5}
set()


In [86]:
a={1,2,3}
b={3,4,5}

In [87]:
print(a | b) # a union b

{1, 2, 3, 4, 5}


In [88]:
print(a & b) # a intersection b

{3}


In [90]:
print (a - b)# a minus/difference b

{1, 2}


In [91]:
print (b - a)# b minus/difference a

{4, 5}


In [101]:
#Dictionary
# {key:value} -> Pair
# key can't be duplicated
# values can've duplicate data

a={'eid':100}
print(a,type(a))

{'eid': 100} <class 'dict'>


In [104]:
a={'eid':100,'name':'Bala','role':'Data Scientist'}
print(a,type(a))
a

{'eid': 100, 'name': 'Bala', 'role': 'Data Scientist'} <class 'dict'>


{'eid': 100, 'name': 'Bala', 'role': 'Data Scientist'}

In [105]:
print(a['eid'])
print(a['name'])
print(a['role'])



100
Bala
Data Scientist


In [106]:
print(a.keys())
print(a.values())

dict_keys(['eid', 'name', 'role'])
dict_values([100, 'Bala', 'Data Scientist'])


#Added below sets for Class Test

In [3]:
import numpy as np

In [10]:
a = np.array([1,2,3,4])
print(a.shape)
print(a)
a=np.array([[1],[2],[3],[4]])
print(a.shape)
print(a)

(4,)
[1 2 3 4]
(4, 1)
[[1]
 [2]
 [3]
 [4]]


In [14]:
a=np.array([[[1,2]],[[2,3]],[[3,4]],[[4,5]]])
print(a.shape)
print(a)

(4, 1, 2)
[[[1 2]]

 [[2 3]]

 [[3 4]]

 [[4 5]]]


In [27]:
a=np.array(range(6))
print(a)
b=a.reshape(3,2)
print(b,b.shape)
b.flatten()

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]] (3, 2)


array([0, 1, 2, 3, 4, 5])

In [28]:
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [31]:
for i in b:
    print(i)
    for j in i:
        print(j)

[0 1]
0
1
[2 3]
2
3
[4 5]
4
5


In [33]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [34]:
import pandas as pd

In [42]:
a=pd.DataFrame(np.array(range(1,10,1)).reshape(3,3),index=["row1","row2","row3"],columns=["col1","col2","col3"])
print(a,type(a))
a

      col1  col2  col3
row1     1     2     3
row2     4     5     6
row3     7     8     9 <class 'pandas.core.frame.DataFrame'>


col1  col2  col3
row1     1     2     3
row2     4     5     6
row3     7     8     9

In [48]:
a.loc["row1"]["col1"]

1

In [53]:
a.iloc[0][2]

/var/folders/8b/_vkggsks1pvdn519cywyj0_40000gn/T/ipykernel_17814/1865342783.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  a.iloc[0][2]


3

In [63]:
a.loc["row1","row2"]

KeyError: 'row2'

In [67]:
a.loc[["row1","row2"]][["col1","col2"]]

col1  col2
row1     1     2
row2     4     5

In [71]:
a.iloc[0:2]

col1  col2  col3
row1     1     2     3
row2     4     5     6

In [82]:
a.iloc[0:2,0:2]

col1  col2
row1     1     2
row2     4     5

In [85]:
a.iloc[0:2,[0,2]]

col1  col3
row1     1     3
row2     4     6

In [87]:
a.loc[a('col1')%2==0]

TypeError: 'DataFrame' object is not callable

In [88]:
a.loc(a['col1']%2==0)

TypeError: unhashable type: 'Series'

In [96]:
print(a)
print(a.loc[a['col1']%2==0])
print(a.loc[a['col2']%2==0])
print(a.loc[a['col3']%2==0])
print(a.loc[a['col3']%2!=0])


      col1  col2  col3
row1     1     2     3
row2     4     5     6
row3     7     8     9
      col1  col2  col3
row2     4     5     6
      col1  col2  col3
row1     1     2     3
row3     7     8     9
      col1  col2  col3
row2     4     5     6
      col1  col2  col3
row1     1     2     3
row3     7     8     9


In [101]:
a=pd.read_csv('/Users/bkannadasan/Documents/GitHub/DataScience/Python/Pandas_Basics/tm_employee_output.csv')
print(a)

   EmployeeID    Name Department  Salary
0           1    Amar         HR   60000
1           2   Akbar         IT   80000
2           3  Antony    Finance   75000


In [104]:
pd.read_csv('/Users/bkannadasan/Documents/GitHub/DataScience/Python/Pandas_Basics/tm_employee_output.csv',index_col=0)


Name Department  Salary
EmployeeID                           
1             Amar         HR   60000
2            Akbar         IT   80000
3           Antony    Finance   75000

In [109]:
a.isna().sum()

EmployeeID    0
Name          0
Department    0
Salary        0
dtype: int64

In [111]:
a[:1]

EmployeeID  Name Department  Salary
0           1  Amar         HR   60000

In [113]:
a.iloc[:1]

EmployeeID  Name Department  Salary
0           1  Amar         HR   60000

In [146]:
df = pd.DataFrame({'A':[34, 78, 54], 'B':[12, 67, 43]})
df = pd.DataFrame({'A':[34, 78, 54], 'B':[12, 67, 43]},index=['r1','r2','r3'])
print(df[df['B']>50])
print(df['B']>50)
print(df[df.B>50])
print('test')
print(df.loc[['r1']])

print(df.loc[['r1'][:1]])




     A   B
r2  78  67
r1    False
r2     True
r3    False
Name: B, dtype: bool
     A   B
r2  78  67
test
     A   B
r1  34  12
     A   B
r1  34  12


In [151]:
df.loc[1,'r1']

KeyError: 'r1'

In [153]:
df.loc['r1'].unique()

array([34, 12])

In [156]:
len(df)

3

In [161]:
df.dtypes

A    int64
B    int64
dtype: object

In [164]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, r1 to r3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
dtypes: int64(2)
memory usage: 180.0+ bytes


In [166]:
df.describe

<bound method NDFrame.describe of      A   B
r1  34  12
r2  78  67
r3  54  43>

In [167]:
df.describe()

A          B
count   3.000000   3.000000
mean   55.333333  40.666667
std    22.030282  27.574142
min    34.000000  12.000000
25%    44.000000  27.500000
50%    54.000000  43.000000
75%    66.000000  55.000000
max    78.000000  67.000000

In [ ]:
np.loa